# Generated by Django 4.2.2 on 2023-07-11 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategories',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
