# Generated by Django 4.2.2 on 2023-07-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_productcategories_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
