# Generated by Django 4.2.2 on 2023-07-12 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be in the correct U.S number format', regex='^\\+?1?\\d{9, 15}$')])),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
