# Generated by Django 4.2.2 on 2023-07-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
