# Generated by Django 4.2.2 on 2023-07-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_productcategories_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Order Date')),
                ('special_instruction', models.CharField(max_length=256, verbose_name='Special Instruction')),
                ('products', models.ManyToManyField(to='home.product')),
            ],
        ),
    ]
