# Generated by Django 4.2.2 on 2023-07-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_productcategory_options_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
