# Generated by Django 4.2.2 on 2023-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_updated_at_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(to='home.order'),
        ),
    ]
