# Generated by Django 4.2.2 on 2023-07-27 01:01

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='home.order'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=home.models.user_profile_pic_default, upload_to=home.models.user_profile_pic_path),
        ),
    ]
