# Generated by Django 4.2.3 on 2023-07-27 09:39

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.user_profile_pic_path),
        ),
    ]
